#!/usr/bin/env python3
"""把组装好的规则（build/data/）编译成 mihomo（Clash.Meta）可直接消费的 rule-provider。

输入：
    build/data/<tag>      由 scripts/assemble_data.py 合并三层并解析聚合组后的规则
                          （**不要**直接读 data/domains|extra|upstream —— 那样会漏掉聚合，
                           实测踩过：客户端只引 advert.com 却漏掉手工补进 advert.gg 的域名）
    data/ip/<name>.txt    自持 IP（每行一个 IP/CIDR）

输出：
    dist/clash/<tag>.yaml            behavior: domain    （仅 domain/full 条目）
    dist/clash/<tag>.classical.yaml  behavior: classical （含 keyword/regexp 时改用这个）
    dist/clash/<name>-ip.yaml        behavior: ipcidr    （来自 data/ip）
    dist/clash/MANIFEST.json         每个文件的 behavior / 条数 / sha256

设计取舍：
  - 同一份组装结果同时供 Clash 与 Xray 使用（单一真相），避免两处维护漂移。
  - keyword/regexp 无法用 `behavior: domain` 表达，此时**改用 classical 输出**并明确提示，
    不静默丢弃（否则「规则看起来在，实际不生效」最难查）。
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "build" / "data"          # 组装后的规则
IP_DIR = ROOT / "data" / "ip"
OUT_DIR = ROOT / "dist" / "clash"


def parse_domain_list(path: pathlib.Path) -> tuple[list[str], list[str], list[str]]:
    """解析 dlc 语法，返回 (domain/full 条目, keyword/regexp 条目, 警告)。"""
    plain: list[str] = []
    special: list[str] = []
    warnings: list[str] = []
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if "@" in line:
            line, _, attrs = line.partition("@")
            warnings.append(f"{path.name}:{lineno} 忽略属性 @{attrs.strip()}")
            line = line.strip()
        if line.startswith("include:"):
            warnings.append(f"{path.name}:{lineno} 跳过 include:"
                            f"{line.split(':', 1)[1]}（组装阶段应已展开）")
            continue
        if line.startswith("domain:"):
            plain.append("+." + line.split(":", 1)[1].strip())
        elif line.startswith("full:"):
            plain.append(line.split(":", 1)[1].strip())
        elif line.startswith("keyword:"):
            special.append("DOMAIN-KEYWORD," + line.split(":", 1)[1].strip())
        elif line.startswith("regexp:"):
            special.append("DOMAIN-REGEX," + line.split(":", 1)[1].strip())
        elif ":" in line:
            warnings.append(f"{path.name}:{lineno} 无法识别的前缀，按纯域名处理：{line}")
            plain.append("+." + line)
        else:
            plain.append("+." + line)
    return plain, special, warnings


def parse_ip_list(path: pathlib.Path) -> tuple[list[str], list[str]]:
    ips: list[str] = []
    warnings: list[str] = []
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if not re.match(r"^[0-9a-fA-F:.]+(/\d{1,3})?$", line):
            warnings.append(f"{path.name}:{lineno} 不是合法 IP/CIDR，已跳过：{line}")
            continue
        ips.append(line)
    return ips, warnings


def dump_yaml(name: str, behavior: str, payload: list[str], sources: list[str]) -> str:
    head = (f"# {name} — generated by scripts/build_clash.py, DO NOT EDIT\n"
            f"# behavior: {behavior}   entries: {len(payload)}\n"
            f"# sources: {', '.join(sources)}\n"
            f"payload:\n")
    return head + "".join(f"  - '{item}'\n" for item in payload)


def main() -> int:
    if not DATA.is_dir() or not any(DATA.iterdir()):
        print(f"❌ 缺 {DATA.relative_to(ROOT)}（先跑 scripts/assemble_data.py）")
        return 2

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUT_DIR.glob("*.yaml"):
        stale.unlink()

    manifest: list[dict] = []
    problems: list[str] = []

    for path in sorted(DATA.glob("*")):
        if not path.is_file() or path.name.startswith("."):
            continue
        tag = path.name
        plain, special, warns = parse_domain_list(path)
        problems.extend(warns)
        plain = sorted(set(plain))
        special = sorted(set(special))
        sources = [f"build/data/{tag}"]

        if not plain and not special:
            problems.append(f"{tag}: 组装结果为空，跳过（确认是否漏填）")
            continue

        if special:
            payload = []
            for item in plain:
                payload.append(("DOMAIN-SUFFIX," + item[2:]) if item.startswith("+.")
                               else ("DOMAIN," + item))
            payload.extend(special)
            out = OUT_DIR / f"{tag}.classical.yaml"
            out.write_text(dump_yaml(tag, "classical", payload, sources),
                           encoding="utf-8", newline="\n")
            behavior, n_entries = "classical", len(payload)
            problems.append(
                f"{tag}: 含 keyword/regexp → 输出 classical（rule-provider 的 behavior 要配 "
                f"classical），文件 {out.name}")
        else:
            out = OUT_DIR / f"{tag}.yaml"
            out.write_text(dump_yaml(tag, "domain", plain, sources),
                           encoding="utf-8", newline="\n")
            behavior, n_entries = "domain", len(plain)

        manifest.append({
            "name": tag, "file": out.name, "sources": sources, "behavior": behavior,
            "entries": n_entries, "sha256": hashlib.sha256(out.read_bytes()).hexdigest(),
        })

    # IP 列表（只来自 data/ip）
    for path in sorted(IP_DIR.glob("*.txt")):
        ips, warns = parse_ip_list(path)
        problems.extend(warns)
        name = path.stem
        if not ips:
            problems.append(f"{path.name}: 无有效条数，跳过（只有注释属预期）")
            continue
        out_name = f"{name}-ip.yaml"
        out = OUT_DIR / out_name
        out.write_text(dump_yaml(name, "ipcidr", sorted(set(ips)),
                                 [f"data/ip/{path.name}"]),
                       encoding="utf-8", newline="\n")
        manifest.append({
            "name": f"{name}-ip", "file": out_name, "sources": [f"data/ip/{path.name}"],
            "behavior": "ipcidr", "entries": len(set(ips)),
            "sha256": hashlib.sha256(out.read_bytes()).hexdigest(),
        })

    (OUT_DIR / "MANIFEST.json").write_text(
        json.dumps({"generated_by": "scripts/build_clash.py", "artifacts": manifest},
                   ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8", newline="\n")

    print(f"生成 {len(manifest)} 个 rule-provider → {OUT_DIR.relative_to(ROOT)}/")
    for item in manifest:
        print(f"  {item['name']:<14} {item['file']:<28} {item['behavior']:<10} "
              f"{item['entries']:>7} 条")
    if problems:
        print("\n注意：")
        for p in problems:
            print(f"  - {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
