#!/usr/bin/env python3
"""把自持规则编译成 mihomo（Clash.Meta）可直接消费的 rule-provider。

输入：
    data/domains/<name>     v2fly domain-list 语法（dlc 同款）
    data/ip/<name>.txt      每行一个 IP/CIDR

输出：
    dist/clash/<name>.yaml            behavior: domain    （仅 domain/full 条目）
    dist/clash/<name>.classical.yaml  behavior: classical （含 keyword/regexp 时改用这个）
    dist/clash/<name>.yaml            behavior: ipcidr    （来自 data/ip）
    dist/clash/MANIFEST.json          每个文件的 behavior / 条数 / sha256
    dist/MANIFEST.sha256              全部产物的 sha256（含 xray dat）

设计取舍：
  - 同一份自持数据同时供 Clash 与 Xray 使用（单一真相），避免两处维护漂移。
  - keyword/regexp 无法用 `behavior: domain` 表达，此时**改用 classical 输出**并明确提示，
    不静默丢弃（否则「规则看起来在，实际不生效」最难查）。
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOMAIN_DIR = ROOT / "data" / "domains"
IP_DIR = ROOT / "data" / "ip"
OUT_DIR = ROOT / "dist" / "clash"

HANDLED = ("domain:", "full:", "keyword:", "regexp:", "include:", "ext:")


def parse_domain_list(path: pathlib.Path) -> tuple[list[str], list[str], list[str]]:
    """解析 dlc 语法，返回 (domain/full 条目, keyword/regexp 条目, 警告)。"""
    plain: list[str] = []
    special: list[str] = []
    warnings: list[str] = []
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        # 属性（@ads 之类）在 mihomo 侧没有对应物：去掉但提示
        if "@" in line:
            line, _, attrs = line.partition("@")
            warnings.append(f"{path.name}:{lineno} 忽略属性 @{attrs.strip()}")
            line = line.strip()
        if line.startswith("include:"):
            warnings.append(f"{path.name}:{lineno} 跳过 include:{line.split(':', 1)[1]}"
                            "（本仓规则不含 include；需要合并公共列表见 sources.yaml）")
            continue
        if line.startswith("domain:"):
            plain.append("+." + line.split(":", 1)[1].strip())
        elif line.startswith("full:"):
            plain.append(line.split(":", 1)[1].strip())
        elif line.startswith("keyword:"):
            special.append("DOMAIN-KEYWORD," + line.split(":", 1)[1].strip())
        elif line.startswith("regexp:"):
            special.append("DOMAIN-REGEX," + line.split(":", 1)[1].strip())
        elif ":" in line and not line.startswith(("domain", "full", "keyword", "regexp")):
            warnings.append(f"{path.name}:{lineno} 无法识别的前缀，按纯域名处理：{line}")
            plain.append("+." + line)
        else:
            # 裸域名按 domain: 处理（dlc 的默认语义）
            plain.append("+." + line)
    return plain, special, warnings


def parse_ip_list(path: pathlib.Path) -> tuple[list[str], list[str]]:
    ips: list[str] = []
    warnings: list[str] = []
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if not re.match(r"^[0-9a-fA-F:.]+(/\d{1,3})?$", line):
            warnings.append(f"{path.name}:{lineno} 不是合法 IP/CIDR，已跳过：{line}")
            continue
        ips.append(line)
    return ips, warnings


def dump_yaml(name: str, behavior: str, payload: list[str]) -> str:
    head = (f"# {name} — generated by scripts/build_clash.py, DO NOT EDIT\n"
            f"# behavior: {behavior}   entries: {len(payload)}\n"
            f"payload:\n")
    body = "".join(f"  - '{item}'\n" for item in payload)
    return head + body


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUT_DIR.glob("*.yaml"):
        stale.unlink()

    manifest: list[dict] = []
    problems: list[str] = []

    # 域名列表
    for path in sorted(DOMAIN_DIR.glob("*")):
        if not path.is_file() or path.name.startswith("."):
            continue
        plain, special, warns = parse_domain_list(path)
        problems.extend(warns)
        if not plain and not special:
            problems.append(f"{path.name}: 列表为空，跳过（需确认是否漏填）")
            continue
        if special:
            payload = []
            for item in plain:
                if item.startswith("+."):
                    payload.append("DOMAIN-SUFFIX," + item[2:])
                else:
                    payload.append("DOMAIN," + item)
            payload.extend(special)
            out = OUT_DIR / f"{path.name}.classical.yaml"
            out.write_text(dump_yaml(path.name, "classical", payload),
                           encoding="utf-8", newline="\n")
            problems.append(
                f"{path.name}: 含 keyword/regexp → 输出 classical（behavior 请配 classical），"
                f"文件 {out.name}")
        else:
            out = OUT_DIR / f"{path.name}.yaml"
            out.write_text(dump_yaml(path.name, "domain", plain),
                           encoding="utf-8", newline="\n")
        payload_len = len(payload) if special else len(plain)
        manifest.append({
            # name = Clash 配置里 rule-providers 的键名，必须唯一
            "name": out.name[:-len(".yaml")].replace(".classical", ""),
            "file": out.name,
            "source": f"data/domains/{path.name}",
            "behavior": "classical" if special else "domain",
            "entries": payload_len,
            "sha256": hashlib.sha256(out.read_bytes()).hexdigest(),
        })

    # IP 列表
    for path in sorted(IP_DIR.glob("*.txt")):
        ips, warns = parse_ip_list(path)
        problems.extend(warns)
        name = path.stem
        if not ips:
            problems.append(f"{path.name}: 无有效条数，跳过（当前只有注释属预期）")
            continue
        # ⚠️ 输出名必须带 -ip 后缀：域名列表 data/domains/self-direct 也会输出
        # self-direct.yaml，同名会互相覆盖（少一个文件还很难察觉）。
        out_name = f"{name}-ip.yaml"
        out = OUT_DIR / out_name
        out.write_text(dump_yaml(name, "ipcidr", ips), encoding="utf-8", newline="\n")
        manifest.append({
            # IP 列表的 provider 名带 -ip 后缀，避免与同名域名列表撞名
            "name": out_name[:-len(".yaml")], "file": out_name,
            "source": f"data/ip/{path.name}", "behavior": "ipcidr",
            "entries": len(ips), "sha256": hashlib.sha256(out.read_bytes()).hexdigest(),
        })

    (OUT_DIR / "MANIFEST.json").write_text(
        json.dumps({"generated_by": "scripts/build_clash.py", "artifacts": manifest},
                   ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8", newline="\n")

    print(f"生成 {len(manifest)} 个 rule-provider → {OUT_DIR.relative_to(ROOT)}/")
    for item in manifest:
        print(f"  {item['name']:<18} {item['file']:<30} behavior={item['behavior']:<10} "
              f"entries={item['entries']:<4} ← {item['source']}")
    if problems:
        print("\n注意：")
        for p in problems:
            print(f"  - {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
